//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Youtube.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class video
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public video()
        {
            this.comments = new HashSet<comment>();
            this.video_like_dislike = new HashSet<video_like_dislike>();
        }
    
        public byte video_id { get; set; }
        public string video_name { get; set; }
        public string video_description { get; set; }
        public HttpPostedFileBase ImageFile { get; set; }
        public string video_icon { get; set; }
        public string video_url { get; set; }
        public Nullable<byte> video_user_id { get; set; }
        public System.DateTime video_created { get; set; }
        public byte video_views { get; set; }
        public bool video_comments_allowed { get; set; }
        public bool video_banned { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<comment> comments { get; set; }
        public virtual user user { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<video_like_dislike> video_like_dislike { get; set; }
    }
}
